
version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    image: flask-vue:dev
    container_name: flask-vue-dev
    ports:
     - "4000:4000"
    volumes:
     - ./app:/app
     - /app/client/node_modules
    environment:
    # flask vars
     - FLASK_HOST=0.0.0.0
     - FLASK_PORT=80
     - FLASK_APP=main.py
     - FLASK_DEBUG=1
    # webpack server host and port
     - HOST=0.0.0.0
     - PORT=4000
    command: /usr/bin/supervisord
